[general]
import = [
  "~/.config/alacritty/colors.toml"
]

[terminal]
shell = { program = "/usr/bin/zsh" }

[env]
TERM = "xterm-256color"

[window]
padding = { x = 32, y = 32 }
dynamic_padding = true
opacity = 0.98
decorations = "None"

[font]
size = 10.5

[font.normal]
family = "JetBrainsMono Nerd Font"
