# Matugen â†’ Alacritty (Dark scheme)

[colors]
transparent_background_colors = true

[colors.primary]
background = "#0e1514"
foreground = "#dde4e2"

[colors.cursor]
text = "#0e1514"
cursor = "#81d5cc"

[colors.selection]
text = "#cce8e4"
background = "#324b48"

[colors.normal]
black   = "#0e1514"
red     = "#ffb4ab"
green   = "#afc9e7"
yellow  = "#b0ccc8"
blue    = "#81d5cc"
magenta = "#00504b"
cyan    = "#2f4962"
white   = "#dde4e2"

[colors.bright]
black   = "#3f4947"
red     = "#93000a"
green   = "#2f4962"
yellow  = "#324b48"
blue    = "#00504b"
magenta = "#b0ccc8"
cyan    = "#afc9e7"
white   = "#bec9c6"
