# Matugen â†’ Alacritty (Dark scheme)

[colors]
transparent_background_colors = true

[colors.primary]
background = "#18120b"
foreground = "#ede0d4"

[colors.cursor]
text = "#18120b"
cursor = "#f3bd6e"

[colors.selection]
text = "#fadebc"
background = "#56442a"

[colors.normal]
black   = "#18120b"
red     = "#ffb4ab"
green   = "#b7cea2"
yellow  = "#ddc2a1"
blue    = "#f3bd6e"
magenta = "#624000"
cyan    = "#3a4c2a"
white   = "#ede0d4"

[colors.bright]
black   = "#4f4539"
red     = "#93000a"
green   = "#3a4c2a"
yellow  = "#56442a"
blue    = "#624000"
magenta = "#ddc2a1"
cyan    = "#b7cea2"
white   = "#d3c4b4"
