[[mgr.prepend_keymap]]
on   = "t"
run  = "shell --orphan -- alacritty --class FloatTerm --working-directory \"$PWD\""
desc = "Open floating terminal here"


[[mgr.prepend_keymap]]
on = "e"
run = "shell --orphan -- alacritty --working-directory \"$PWD\" -e nvim \"$@\""
desc = "Open file in new nvim terminal"
