[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.nwgdock]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/nwg-dock-hyprland/colors.css'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'
post_hook = 'pkill fuzzel || true'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/themes/Matugen.conf"

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.nwg_drawer]
input_path = "~/.config/matugen/templates/nwg-drawer.css"
output_path = "~/.config/nwg-drawer/drawer.css"
post_hook = "pkill -x nwg-drawer 2>/dev/null || true"