# Matugen â†’ Alacritty (Dark scheme)

[colors]
transparent_background_colors = true

[colors.primary]
background = "{{colors.background.dark.hex}}"
foreground = "{{colors.on_background.dark.hex}}"

[colors.cursor]
text = "{{colors.background.dark.hex}}"
cursor = "{{colors.primary.dark.hex}}"

[colors.selection]
text = "{{colors.on_secondary_container.dark.hex}}"
background = "{{colors.secondary_container.dark.hex}}"

[colors.normal]
black   = "{{colors.surface.dark.hex}}"
red     = "{{colors.error.dark.hex}}"
green   = "{{colors.tertiary.dark.hex}}"
yellow  = "{{colors.secondary.dark.hex}}"
blue    = "{{colors.primary.dark.hex}}"
magenta = "{{colors.primary_container.dark.hex}}"
cyan    = "{{colors.tertiary_container.dark.hex}}"
white   = "{{colors.on_surface.dark.hex}}"

[colors.bright]
black   = "{{colors.surface_variant.dark.hex}}"
red     = "{{colors.error_container.dark.hex}}"
green   = "{{colors.tertiary_container.dark.hex}}"
yellow  = "{{colors.secondary_container.dark.hex}}"
blue    = "{{colors.primary_container.dark.hex}}"
magenta = "{{colors.secondary.dark.hex}}"
cyan    = "{{colors.tertiary.dark.hex}}"
white   = "{{colors.on_surface_variant.dark.hex}}"
